### ISSUE TITLE
Problems with c_analyze_text

### ISSUE THREAD

**Issue by tonypearson** [Call-for-Code-for-Racial-Justice/Legit-Info#73]
(Legit-Info) [Yoga Legit-Info]$ ./stage1 qcluster
**Using SQLite3**
18:06:09 [Q] INFO Q Cluster ten-purple-maryland-nevada starting.
18:06:09 [Q] INFO Process-1:1 ready for work at 29372
18:06:09 [Q] INFO Process-1:2 ready for work at 29373
18:06:09 [Q] INFO Process-1:3 ready for work at 29374
18:06:09 [Q] INFO Process-1:4 ready for work at 29375
18:06:09 [Q] INFO Process-1:5 monitoring at 29376
18:06:09 [Q] INFO Process-1 guarding cluster ten-purple-maryland-nevada
18:06:09 [Q] INFO Process-1:6 pushing tasks at 29377
18:06:09 [Q] INFO Q Cluster ten-purple-maryland-nevada running.
18:11:09 [Q] INFO Enqueued 37
18:11:09 [Q] INFO Process-1 created a task from schedule [c_analyze_text]
18:11:10 [Q] INFO Process-1:1 processing [kansas-ink-pizza-freddie]
05-27 18:11:10 tasks:c_analyze_text [INFO] 76:task started: c_analyze_text
05-27 18:11:12 log_time:time_now [INFO] Starting analyze_text at May-27 11:11AM MST
18:11:12 [Q] ERROR Failed [kansas-ink-pizza-freddie] - Cannot resolve keyword 'text' into field. Choices are: criteria, date_added, id, iname, laws, profile : Traceback (most recent call last):
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/home/tpearson/Develop/Legit-Info/cfc_app/tasks.py", line 82, in c_analyze_text
    call_command(cmd, '--api', '--skip', '--compare')
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 138, in handle
    impacts = Impact.objects.all().exclude(text='None')
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/query.py", line 950, in exclude
    return self._filter_or_exclude(True, *args, **kwargs)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/query.py", line 967, in _filter_or_exclude_inplace
    self._query.add_q(~Q(*args, **kwargs))
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1380, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1258, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1084, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'text' into field. Choices are: criteria, date_added, id, iname, laws, profile

**Comment by tonypearson** [comment]
analyze_text was doing Impact...Exclude(text='None') but the "text" field has been renamed to "iname".  Fixed.

**Comment by tonypearson** [comment]
05-27 18:32:27 Oneline:Oneline_parse_header [WARNING] Headers not found in text file. A Z - H B 2 0 0 4 - 1 7 1 7 - Y 2 0 1 9 . h t m l   2 0 1 9 - 1 1 - 1 9   _ T I 
05-27 18:32:27 analyze_text:process_state [INFO] 238:No bill_id found, removing: AZ-HB2004-1717-Y2019.txt

**Comment by tonypearson** [comment]
More problems:
20:38:08 [Q] INFO Process-1 created a task from schedule [c_analyze_text]
20:38:08 [Q] INFO Process-1:3 processing [eight-charlie-william-west]
05-27 20:38:08 tasks:c_analyze_text [INFO] 76:task started: c_analyze_text
05-27 20:38:11 log_time:time_now [INFO] Starting analyze_text at May-27 01:38PM MST
05-27 20:38:11 analyze_text:handle [INFO] 150:Processing: United States (US)
05-27 20:39:55 analyze_text:handle [ERROR] 151:Process State Error: get() returned more than one Law -- it returned 2!
Traceback (most recent call last):
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 162, in handle
    self.process_state(state)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 188, in process_state
    self.process_legislation(filename, textdata, header)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 269, in process_legislation
    self.save_law(key, header, rel, imp_chosen)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 343, in save_law
    law = Law.objects.get(key=key)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/query.py", line 436, in get
    num if not limit or num < limit else 'more than %s' % (limit - 1),
cfc_app.models.Law.MultipleObjectsReturned: get() returned more than one Law -- it returned 2!
20:39:55 [Q] ERROR Failed [eight-charlie-william-west] - 151:Process State Error: get() returned more than one Law -- it returned 2! : Traceback (most recent call last):
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 162, in handle
    self.process_state(state)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 188, in process_state
    self.process_legislation(filename, textdata, header)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 269, in process_legislation
    self.save_law(key, header, rel, imp_chosen)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 343, in save_law
    law = Law.objects.get(key=key)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/query.py", line 436, in get
    num if not limit or num < limit else 'more than %s' % (limit - 1),
cfc_app.models.Law.MultipleObjectsReturned: get() returned more than one Law -- it returned 2!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/home/tpearson/Develop/Legit-Info/cfc_app/tasks.py", line 82, in c_analyze_text
    call_command(cmd, '--api', '--skip', '--compare')
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 166, in handle
    raise AnalyzeTextError(err_msg) from exc
cfc_app.management.commands.analyze_text.AnalyzeTextError: 151:Process State Error: get() returned more than one Law -- it returned 2!

**Comment by tonypearson** [comment]
Added .first() to get the first that matches the key.

**Comment by tonypearson** [comment]
.first() did not seem to solve the issue.  Problem is two records with same key in law database.

21:28:15 [Q] INFO Enqueued 44
21:28:15 [Q] INFO Process-1 created a task from schedule [c_analyze_text]
21:28:15 [Q] INFO Process-1:1 processing [mike-texas-butter-edward]
05-27 21:28:15 tasks:c_analyze_text [INFO] 76:task started: c_analyze_text
05-27 21:28:19 log_time:time_now [INFO] Starting analyze_text at May-27 02:28PM MST
05-27 21:28:19 analyze_text:handle [INFO] 150:Processing: United States (US)
05-27 21:30:21 analyze_text:handle [ERROR] 151:Process State Error: get() returned more than one Law -- it returned 2!
Traceback (most recent call last):
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 162, in handle
    self.process_state(state)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 188, in process_state
    self.process_legislation(filename, textdata, header)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 269, in process_legislation
    self.save_law(key, header, rel, imp_chosen)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 344, in save_law
    law = Law.objects.get(key=key).first()
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/query.py", line 436, in get
    num if not limit or num < limit else 'more than %s' % (limit - 1),
cfc_app.models.Law.MultipleObjectsReturned: get() returned more than one Law -- it returned 2!
21:30:21 [Q] ERROR Failed [mike-texas-butter-edward] - 151:Process State Error: get() returned more than one Law -- it returned 2! : Traceback (most recent call last):
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 162, in handle
    self.process_state(state)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 188, in process_state
    self.process_legislation(filename, textdata, header)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 269, in process_legislation
    self.save_law(key, header, rel, imp_chosen)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 344, in save_law
    law = Law.objects.get(key=key).first()
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/db/models/query.py", line 436, in get
    num if not limit or num < limit else 'more than %s' % (limit - 1),
cfc_app.models.Law.MultipleObjectsReturned: get() returned more than one Law -- it returned 2!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/home/tpearson/Develop/Legit-Info/cfc_app/tasks.py", line 82, in c_analyze_text
    call_command(cmd, '--api', '--skip', '--compare')
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/home/tpearson/.local/share/virtualenvs/Legit-Info-YLTR15_m/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/tpearson/Develop/Legit-Info/cfc_app/management/commands/analyze_text.py", line 166, in handle
    raise AnalyzeTextError(err_msg) from exc
cfc_app.management.commands.analyze_text.AnalyzeTextError: 151:Process State Error: get() returned more than one Law -- it returned 2!
