### ISSUE TITLE
Error in analyze_text job

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Legit-Info#79]
I get the following error when running the analyze_text job:

```
Jun 7 17:40:44 Code Engine legit-info-job-analyzetext-jobrun-mzxss-0-2 django.db.utils.DataError: value too long for type character varying(1000)
Jun 7 17:40:44 Code Engine legit-info-job-analyzetext-jobrun-mzxss-0-2 AnalyzeTextError: 151:Process State Error: value too long for type character varying(1000)
Jun 7 17:40:44 Code Engine legit-info-job-analyzetext-jobrun-mzxss-0-3 **Using PostgreSQL**
Jun 7 17:41:28 Code Engine legit-info-job-analyzetext-jobrun-mzxss-0-3 06-08 00:41:23 analyze_text:handle [ERROR] 151:Process State Error: value too long for type character varying(1000)
Jun 7 17:41:28 Code Engine legit-info-job-analyzetext-jobrun-mzxss-0-3 Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
Jun 7 17:41:28 Code Engine legit-info-job-analyzetext-jobrun-mzxss-0-3 psycopg2.errors.StringDataRightTruncation: value too long for type character varying(1000)
Jun 7 17:41:28 Code Engine legit-info-job-analyzetext-jobrun-mzxss-0-3 The above exception was the direct cause of the following exception:
Jun 7 17:41:28 Code Engine legit-info-job-analyzetext-jobrun-mzxss-0-3 Traceback (most recent call last):
  File "/opt/app-root/src/cfc_app/management/commands/analyze_text.py", line 162, in handle
    self.process_state(state)
  File "/opt/app-root/src/cfc_app/management/commands/analyze_text.py", line 188, in process_state
    self.process_legislation(filename, textdata, header)
  File "/opt/app-root/src/cfc_app/management/commands/analyze_text.py", line 269, in process_legislation
    self.save_law(key, header, rel, imp_chosen)
  File "/opt/app-root/src/cfc_app/management/commands/analyze_text.py", line 370, in save_law
    law.save()
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
Jun 7 17:41:28 Code Engine legit-info-job-analyzetext-jobrun-mzxss-0-3 django.db.utils.DataError: value too long for type character varying(1000)
Jun 7 17:41:28 Code Engine legit-info-job-analyzetext-jobrun-mzxss-0-3 AnalyzeTextError: 151:Process State Error: value too long for type character varying(1000)
```

**Comment by upkarlidder** [comment]
Fixed. @tonypearson increased the max allowed value to 1000.
