### ISSUE TITLE
Error in legit-info-job-analyzetext - value too long for type character varying(800)

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Legit-Info#86]
Relevance attribute of Law model can only accommodate 800 characters:

https://github.com/Call-for-Code-for-Racial-Justice/Legit-Info/blob/5e4f8d8faf5f7a721e658ec5053fd17aaadda965/cfc_app/models.py#L244

@tonypearson @tnadams: not sure the best way to handle this. Can increase the field to 1000 or truncate relevance? I am not sure where else relevance is being used.

Any more throws this error:
```
Jun 13 18:36:20 Code Engine legit-info-job-analyzetext-jobrun-2xb9n-0-0 06-14 01:36:13 analyze_text:handle [ERROR] 151:Process State Error: value too long for type character varying(800)
Jun 13 18:36:20 Code Engine legit-info-job-analyzetext-jobrun-2xb9n-0-0 Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
Jun 13 18:36:20 Code Engine legit-info-job-analyzetext-jobrun-2xb9n-0-0 psycopg2.errors.StringDataRightTruncation: value too long for type character varying(800)
Jun 13 18:36:20 Code Engine legit-info-job-analyzetext-jobrun-2xb9n-0-0 The above exception was the direct cause of the following exception:
Jun 13 18:36:20 Code Engine legit-info-job-analyzetext-jobrun-2xb9n-0-0 Traceback (most recent call last):
  File "/opt/app-root/src/cfc_app/management/commands/analyze_text.py", line 162, in handle
    self.process_state(state)
  File "/opt/app-root/src/cfc_app/management/commands/analyze_text.py", line 188, in process_state
    self.process_legislation(filename, textdata, header)
  File "/opt/app-root/src/cfc_app/management/commands/analyze_text.py", line 273, in process_legislation
    self.save_law(key, header, rel, imp_chosen)
  File "/opt/app-root/src/cfc_app/management/commands/analyze_text.py", line 376, in save_law
    law.save()
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/base.py", line 872, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/base.py", line 926, in _do_update
    return filtered._update(values) > 0
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/query.py", line 803, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1522, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
Jun 13 18:36:20 Code Engine legit-info-job-analyzetext-jobrun-2xb9n-0-0 .........................................................................................................................................................................................................................Processing: Arizona, USA (AZ)
    return executor(sql, params, many, context)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app-root/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
```

**Comment by tnadams** [comment]
I think this is because the "relevance" column has been defined with an 800 character limit in the database itself. If we want to raise this to 1000, it needs to be done here first then extend the new limit to anywhere else we assign this a value.

https://github.com/Call-for-Code-for-Racial-Justice/Legit-Info/blob/23d502f9ca5309924d33821059874010b85a079c/sources/cfc-law30.sql#L12

        CREATE TABLE "cfc_app_law"(
          id SERIAL UNIQUE,
          "key" VARCHAR(25),
          title VARCHAR(200),
          summary VARCHAR(1000),
          impact_id INT,
          location_id INT,
          bill_id VARCHAR(15),
          doc_date DATE,
          cite_url VARCHAR(200),
          **relevance VARCHAR(800)**
        );

**Comment by upkarlidder** [comment]
Thanks @tnadams. Is the sql file used? I thought the `makemigrations` and `migrate` commands created the database from the models.py file directly. Is the SQL file more for backup?

In either case, if 1000 is the correct length, we can change it in both places. Is that enough? Secondly, what is the `relevance` field used for? What does a relevance like this signify?

```
(NLU)'Medicine' => 'Healthcare', 'Health care' => 'Healthcare', 'Nursing' => 'Healthcare', 'Physician' => 'Healthcare', 'Registered nurse' => 'Healthcare', 'Health care provider' => 'Healthcare', 'Opioid' => 'Healthcare', 'Prescription drug' => 'Healthcare', 'Health' => 'None', 'Drugs' => 'None'
```
